apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespaces.nexusNs }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.role }}
