apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-{{ .Chart.Version }}-{{ .Release.Name }}-create-nexus-workdir-config | trunc 63 | trimSuffix "-"
  namespace: {{ .Values.namespaces.nexusNs }}
data:
   create-nexus-work-dir.sh: |
    #!/bin/bash
    # Make Nexus Repository Manager work directory
    mkdir -p /nexus-repo-mgr-work-dir/work

