apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.workdir.configmap.name }}
  namespace: {{ .Values.namespaces.nexusNs }}
data:
   create-nexus-work-dir.sh: |
    #!/bin/bash
    # Make Nexus Repository Manager work directory
    mkdir -p /nexus-repo-mgr-work-dir/work

